Vagrant.require_plugin('vagrant-lightsail')

Vagrant.configure('2') do |config|
  config.ssh.username         = 'ubuntu'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :lightsail do |provider, override|
    override.vm.box = 'lightsail'
    override.vm.box_url = 'https://github.com/thejandroman/vagrant-lightsail/raw/master/box/lightsail.box'

    provider.ssh_key_name = 'Test Key'
  end
end
