Vagrant.require_plugin('vagrant-lightsail')

Vagrant.configure('2') do |config|
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.allowed_synced_folder_types = [:rsync]
  config.vm.synced_folder '.', '/vagrant', disabled: true, type: 'rsync'

  config.vm.provider :lightsail do |provider, override|
    override.vm.box       = 'lightsail'
    override.vm.box_url   = 'https://github.com/thejandroman/vagrant-lightsail/raw/master/box/lightsail.box'
    override.ssh.username = 'ubuntu'

    provider.keypair_name = 'Test-Key'
    provider.port_info    = [
      { from_port: 22,
        to_port: 22,
        protocol: 'tcp' },
      { from_port: 80,
        to_port: 80,
        protocol: 'udp' },
      { from_port: 443,
        to_port: 443,
        protocol: 'tcp' }
    ]
  end

  config.vm.provision :shell, path: 'scripts/provision.sh'
  config.vm.provision 'puppet' do |puppet|
    puppet.synced_folder_type = 'rsync'
    puppet.environment_path   = 'puppet'
    puppet.environment        = 'lightsail'
  end
end
